# Generated by gallery/generate.py; do not edit.
function laserbridges_gallery:clear
# bridge-white-floor: generated bridge white safe control
setblock 162 100 160 laserbridges:laser_block_powered[color=0,face=floor,facing=north]
# bridge-yellow-wall: generated bridge yellow wall east
setblock 164 100 160 laserbridges:laser_block_powered[color=4,face=wall,facing=east]
# bridge-cyan-ceiling: generated bridge cyan ceiling west
setblock 166 100 160 laserbridges:laser_block_powered[color=9,face=ceiling,facing=west]
# bridge-black-floor: generated bridge black floor south
setblock 168 100 160 laserbridges:laser_block_powered[color=15,face=floor,facing=south]
# fence-white-floor: generated fence white safe control
setblock 162 100 162 laserbridges:laser_fence_powered[color=0,face=floor,facing=north]
# fence-light-blue-wall: generated fence light blue wall south
setblock 164 100 162 laserbridges:laser_fence_powered[color=3,face=wall,facing=south]
# fence-purple-ceiling: generated fence purple ceiling east
setblock 166 100 162 laserbridges:laser_fence_powered[color=10,face=ceiling,facing=east]
# fence-green-wall: generated fence green wall west
setblock 168 100 162 laserbridges:laser_fence_powered[color=13,face=wall,facing=west]
# bridge-source-floor-support: support for unpowered bridge source
setblock 162 99 165 minecraft:stone
# bridge-source-unpowered: orange bridge source unpowered floor
setblock 162 100 165 laserbridges:laser_source_block[color=1,face=floor,facing=north,powered=false]
# fence-source-ceiling-support: support for unpowered fence source
setblock 165 101 165 minecraft:stone
# fence-source-unpowered: pink fence source unpowered ceiling
setblock 165 100 165 laserbridges:laser_fence_source_block[color=6,face=ceiling,facing=south,powered=false]
# stock-control: stone stock rendering control
setblock 171 100 165 minecraft:stone
# natural-bridge-power: redstone support and power for natural bridge row
setblock 160 100 170 minecraft:redstone_block
# natural-bridge-source: blue naturally generated bridge source
setblock 161 100 170 laserbridges:laser_source_block[color=11,face=wall,facing=east,powered=false]
# natural-fence-power: redstone support and power for natural fence row
setblock 160 100 173 minecraft:redstone_block
# natural-fence-source: red naturally generated fence source
setblock 161 100 173 laserbridges:laser_fence_source_block[color=14,face=wall,facing=east,powered=false]
function laserbridges_gallery:verify
