# Generated by gallery/generate.py; do not edit.
function laserbridges_gallery:clear
# stock-control: stone stock rendering control
setblock 176 100 175 minecraft:stone
function laserbridges_gallery:verify
