# Generated by gallery/generate.py; do not edit.
execute unless block 162 100 160 laserbridges:laser_block_powered[color=0,face=floor,facing=north] run tellraw @a {"text":"gallery mismatch: bridge-white-floor","color":"red"}
execute unless block 164 100 160 laserbridges:laser_block_powered[color=4,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: bridge-yellow-wall","color":"red"}
execute unless block 166 100 160 laserbridges:laser_block_powered[color=9,face=ceiling,facing=west] run tellraw @a {"text":"gallery mismatch: bridge-cyan-ceiling","color":"red"}
execute unless block 168 100 160 laserbridges:laser_block_powered[color=15,face=floor,facing=south] run tellraw @a {"text":"gallery mismatch: bridge-black-floor","color":"red"}
execute unless block 162 100 162 laserbridges:laser_fence_powered[color=0,face=floor,facing=north] run tellraw @a {"text":"gallery mismatch: fence-white-floor","color":"red"}
execute unless block 164 100 162 laserbridges:laser_fence_powered[color=3,face=wall,facing=south] run tellraw @a {"text":"gallery mismatch: fence-light-blue-wall","color":"red"}
execute unless block 166 100 162 laserbridges:laser_fence_powered[color=10,face=ceiling,facing=east] run tellraw @a {"text":"gallery mismatch: fence-purple-ceiling","color":"red"}
execute unless block 168 100 162 laserbridges:laser_fence_powered[color=13,face=wall,facing=west] run tellraw @a {"text":"gallery mismatch: fence-green-wall","color":"red"}
execute unless block 162 99 165 minecraft:stone run tellraw @a {"text":"gallery mismatch: bridge-source-floor-support","color":"red"}
execute unless block 162 100 165 laserbridges:laser_source_block[color=1,face=floor,facing=north,powered=false] run tellraw @a {"text":"gallery mismatch: bridge-source-unpowered","color":"red"}
execute unless block 165 101 165 minecraft:stone run tellraw @a {"text":"gallery mismatch: fence-source-ceiling-support","color":"red"}
execute unless block 165 100 165 laserbridges:laser_fence_source_block[color=6,face=ceiling,facing=south,powered=false] run tellraw @a {"text":"gallery mismatch: fence-source-unpowered","color":"red"}
execute unless block 171 100 165 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
execute unless block 160 100 170 minecraft:redstone_block run tellraw @a {"text":"gallery mismatch: natural-bridge-power","color":"red"}
execute unless block 161 100 170 laserbridges:laser_source_block[color=11,face=wall,facing=east,powered=true] run tellraw @a {"text":"gallery mismatch: natural-bridge-source","color":"red"}
execute unless block 162 100 170 laserbridges:laser_block_powered[color=11,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: natural-bridge-first","color":"red"}
execute unless block 168 100 170 laserbridges:laser_block_powered[color=11,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: natural-bridge-middle","color":"red"}
execute unless block 175 100 170 laserbridges:laser_block_powered[color=11,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: natural-bridge-last","color":"red"}
execute unless block 160 100 173 minecraft:redstone_block run tellraw @a {"text":"gallery mismatch: natural-fence-power","color":"red"}
execute unless block 161 100 173 laserbridges:laser_fence_source_block[color=14,face=wall,facing=east,powered=true] run tellraw @a {"text":"gallery mismatch: natural-fence-source","color":"red"}
execute unless block 162 100 173 laserbridges:laser_fence_powered[color=14,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: natural-fence-first","color":"red"}
execute unless block 168 100 173 laserbridges:laser_fence_powered[color=14,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: natural-fence-middle","color":"red"}
execute unless block 175 100 173 laserbridges:laser_fence_powered[color=14,face=wall,facing=east] run tellraw @a {"text":"gallery mismatch: natural-fence-last","color":"red"}
tellraw @a {"text":"Laser Bridges & Doors gallery checked","color":"green"}
